--- #YAML:1.0
name:               Dancer-Plugin-MobileDevice
version:            0.03
abstract:           make a Dancer app mobile-aware
author:
    - Alexis Sukrieh <sukria@sukria.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:      1.3
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
